export const allData = [
    {
        "CompanyName": "Apple",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Google",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Microsoft",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "BU Spark",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Testing",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Google",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Microsoft",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "BU Spark",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Testing",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Google",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Microsoft",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "BU Spark",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Testing",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },    {
        "CompanyName": "Apple",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Google",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Microsoft",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "BU Spark",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Testing",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Google",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Microsoft",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "BU Spark",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Testing",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Google",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Microsoft",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "BU Spark",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Testing",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },    {
        "CompanyName": "Apple",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Google",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Microsoft",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "BU Spark",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Testing",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Google",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Microsoft",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "BU Spark",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Testing",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Google",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Microsoft",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "BU Spark",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    },
    {
        "CompanyName": "Testing",
        "CompanyDescription": "Dsadsad",
        "Notes": "Notes",
        "JobTitle": "Programmer",
        "JobLocation": "NYC",
        "Date": "04/10/2022",
        "Status": "Applied",
        "Link": "https://google.com",
        "did": "dsajdosajd"
    }
];